import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Owner from "@/components/Owner";
import Catalog from "@/components/Catalog";
import Promo from "@/components/Promo";
import Product from "@/components/Product";
import Advantages from "@/components/Advantages";
import Accessories from "@/components/Accessories";
import Packing from "@/components/Packing";
import Features from "@/components/Features";
import Overview from "@/components/Overview";
import Reviews from "@/components/Reviews";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= "body">
        <div className='container'>
        <Header />
        <Owner/>
        <Catalog/>
        {children}
        
        <Promo/>
        <Product/>
        <Advantages/>
        <Packing/>
        <Accessories/>
        <Features/>
        <Overview/>
        <Reviews/>
        <Footer/>
        </div>
        
      </body>
    </html>
  );
}
